version: '3'
services:
  portfolio:
    image: nginx:latest
    container_name: react-portfolio
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mounting directly to nginx.conf file
    restart: always
