version: '3.8'  # Remove if using latest compose spec
services:
  react-portfolio:
    build: .
    ports:
      - "80:80"
    volumes:
      - .\\nginx.conf:/etc/nginx/nginx.conf:ro
      - .\\build:/usr/share/nginx/html:ro
