version: "3"
services:
  portfolio:
    image: nginx:latest
    container_name: react-portfolio
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Ensure this points to the correct file
      - ./build:/usr/share/nginx/html:ro
    restart: always
